phraseapp:
  access_token: 250def7c4fce314e7489457175499b88927a5346e4338370ebc8ce961b78dba3
  project_id: 51631e816f91ab01e8ea566578c94d5f
  push:
    sources:
    - file: ./pt-BR/*.csv
      params:
        file_format: csv
  pull:
    targets:
    - file: ./<locale_code>/pt-BR.csv
      params:
        file_format: csv
    - file: ./<locale_code>/secondsource.csv
      params:
        file_format: csv