phraseapp:
  access_token: 250def7c4fce314e7489457175499b88927a5346e4338370ebc8ce961b78dba3
  project_id: c7575f361d6775b7f83063dce1379d84
  push:
    sources:
    - file: ./pt-BR/<tag>.ptbr.csv
      params:
        file_format: csv
        update_translations: true
        locale_id: 4a2e091f052365cb4678ca46bbf5ed69
  pull:
    targets:
    - file: ./<locale_code>/pt-BR.<locale_name>.csv
      params:
        file_format: csv
        tag: "pt-BR"
        update_translations: true
        locale_id: 5e4308bf798357ce6de6d3433c5aee08
    - file: ./<locale_code>/secondsource.<locale_name>.csv
      params:
        file_format: csv
        tag: "secondsource"
        update_translations: true
        locale_id: 5e4308bf798357ce6de6d3433c5aee08