phraseapp:
  access_token: 250def7c4fce314e7489457175499b88927a5346e4338370ebc8ce961b78dba3
  project_id: da3265f4099b8d0b8419e858ea8660ca
  push:
    sources:
    - file: ./<locale_code>/<tag>.csv
      update_translations: true
      params:
        file_format: csv
        locale_id: 781847f05db6b329af8b327c31c39794
  pull:
    targets:
      # pt-BR
      - file: ./<locale_code>/pt-BR.<locale_name>.csv
        params:
          tag: "pt-BR"
          file_format: csv
      # secondsource
      - file: ./<locale_code>/secondsource.<locale_name>.csv
        params:
          tag: "secondsource"
          file_format: csv