phraseapp:
  access_token: 250def7c4fce314e7489457175499b88927a5346e4338370ebc8ce961b78dba3
  project_id: 51631e816f91ab01e8ea566578c94d5f
  push:
    sources:
    - file: ./pt-BR/pt-BR.csv
      params:
        file_format: csv
        update_translations: true
        locale_id: 0e97c32fc5439843a544b1d21cf5a9f1
    - file: ./pt-BR/secondsource.csv
      params:
        file_format: csv
        update_translations: true
        locale_id: 0e97c32fc5439843a544b1d21cf5a9f1
  pull:
    targets:
    - file: ./<locale_code>/pt-BR.csv
      params:
        file_format: csv
        update_translations: true
        locale_id: afa19ab970ea6926e6115460201f8d8c
    - file: ./<locale_code>/secondsource.csv
      params:
        file_format: csv
        update_translations: true
        locale_id: afa19ab970ea6926e6115460201f8d8c